config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  get 'home/index'

  get 'welcome/index'

  # get 'categories/:category_id', to: 'articles#index', as: :category

  resources :articles do
    resources :comments, module: :articles
  end

  resources :publications do
    resources :comments, module: :publications
  end

  resources :users do
    resources :emergencies, controller: :contacts, type: 'Emergency'
    resources :friends, controller: :contacts, type: 'Friend'
  end

  # resources :categories do
  #  resources :articles
  # end

  resources :verifieds do
    resources :users
    resources :articles
  end


  resources :surveys do

    resources :questions do
      resources :answer_options
    end

  end


  resources :messages

  root to: 'home#index'

end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord # rubocop:todo Style/Documentation
  # dependent: :destroy, actual como una eliminacion en cascada,,
  # en donde a  eliminar el padre (Article) se elimina de igual forma el hijo (Comment)

  has_many :comments, as: :commentable

  # has_and_belongs_to_many :categories #Relacion Many-to-Many a categorias

  has_many :verifieds
  has_many :users, through: :verifieds

  # Upload Attachements
  mount_uploaders :attachments, ImageUploader

  mount_uploaders :attachments, PdfUploader

  # rubocop:todo Style/AsciiComments
  # estamos validando un campo, para el title que sea de 5 caracteres (Tamaño)
  # rubocop:enable Style/AsciiComments
  validates :title, presence: true, length: { minimum: 5 }

  validates :text, presence: true, length: { minimum: 10 }

  def self.category_with(name)
    Category.find_by!(name: name).articles
  end

  def self.category_counts
    Category.select('categories.*, count(categories.Category_id) as count').joins(:categories).group('categories.Category_id')
  end

  def category_list
    categories.map(&:name).join(', ')
  end

  def category_list=(names)
    self.categories = names.split(',').map do |c|
      Category.where(name: c.strip).first_or_create!
    end
  end

  def self.search(search, page)
    where(['upper(title) like ?',
           "%#{search}%".upcase]).paginate(page: page, per_page: 5).order('title')
  end
end

app/controllers/articles/comments_controller.rb
class Articles::CommentsController < CommentsController

  before_action :set_commentable

  private

    def set_commentable
      @commentable = Article.find(params[:article_id])
    end

end

app/controllers/articles_controller.rb
# frozen_string_literal: true

# rubocop:todo Style/Documentation
class ArticlesController  < ApplicationController

  before_action :set_article, only: %i[show edit update] # Sintaxis of rubocop


  # http_basic_authenticate_with name: "admin", password: "123",
  # except: [:index, :show]

  def index
    # params[:category] ? @articles = Article.category_with(params[:category]) :
    @articles = Article.search(params[:search], params[:page])
    @articles = Article.all
    @articles = Article.paginate(page: params[:page])
  end

  def show; end

  # obtenemos el id de modelo de articulo en BD, id = 7
  def edit; end

  def new
    @article = Article.new
  end

  def create
    # render plain: params[:article].inspect
    # utilizamos un variable instancia para instancia un nuevo objeto del Modelo Articulo,
    # y recibe como parametro, en el metodo params,
    # guardar en un array los parametros o campos, del recurso articulos.
    @article = Article.new(article_params)

    # Guardar el Modelo y lo guarda en BD,
    # rubocop:todo Style/AsciiComments
    # Retorna un Valor Booleano (True ó False), si se guardo correctamente o no.
    # rubocop:enable Style/AsciiComments
    # @article.save , es validamos si modelo se guardo correctamente, con una condicion

    if @article.save
      # Renderiza el articulo, alamcena la variable de instancia.
      # Redericiona ala accion show,
      redirect_to @article

    else
      # render, instancia de redirect_to
      render :new # la variable de instcia @article, es pasada a la vista new
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to article_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :text, attachments: [])
  end

  def set_article
    @article = Article.find(params[:id])
  end

end
# rubocop:enable Style/Documentation

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper # rubocop:todo Style/Documentation
end

app/views/articles/_form.html.erb
   <%= form_with(model: @article, local: true) do |form| %>
 
      <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@article.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @article.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
     
      <p>
        <%= form.label :title %><br>
        <%= form.text_field :title, :class => 'form-control' %>
      </p>
     
      <p>
        <%= form.label :text %><br>
        <%= form.text_area :text, :class => 'form-control' %>
      </p>

      <div>
        <%= form.label :attachments %>
        <%= form.file_field :attachments, multiple: true, :class => 'btn btn-outline-secondary' %>
      </div>
          
      <p>
        <%= form.submit 'Guardar', :class => 'btn btn-outline-primary' %>
      </p>

      
     
    <% end %>
    


       
    
  

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
 

<%= render 'form' %>

 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class = "container">

<center><h1>Listing Articles</h1></center>
 
<%= form_tag articles_path, :method => 'get' do %>
<% content_tag :label do %>
Search Article:
<%= text_field_tag :search, params[:search] %>
<%= submit_tag "Buscar", :name => nil, :class => 'btn btn-outline-info btn-sm' %>
<% end %>
<% end %>

<%= link_to 'New article', new_article_path, :class => 'btn btn-outline-primary' %>

<br><br>

<div class="row">
  <% @articles.each do |article| %>
    <div class="col-sm">
  <div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"></h5>
    <p class="card-text">

      <b>Title: </b> <%= article.title %>
      <br>
      <b>Message: </b> <%= article.text %>
    
      <br><br>

      <%= link_to 'Comment(' +article.comments.count.to_s+')', article_comments_path(article), class: 'btn btn-info btn-sm' %>
      <br><br><br>
      <%= link_to 'Show', article_path(article), :class => 'btn btn-outline-primary btn-sm' %>
      
      <%= link_to 'Edit',  edit_article_path(article), :class => 'btn btn-outline-warning btn-sm' %>

      <%= 
          link_to 'Destroy', article_path(article),
          method: :delete,  :class => 'btn btn-outline-danger btn-sm',
          data: { confirm: 'Are you sure?' } 
      %>
        
    </p>
    
  </div>
</div>
<br>
</div>
<% end %>
</div>


<%= will_paginate @articles, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente&raquo;', :class => 'pagination' %>

<br>

<button type="button" class="btn btn-primary">
  Articles: <span class="badge badge-light"><%= @articles.count %></span>
  <span class="sr-only"></span>
</button>
</div>

app/views/articles/new.html.erb
<div class="container" style="margin-top: 30px;">
<center>
<div class="card">
  <h5 class="card-header">New Article</h5>
  <div class="card-body">
    <p class="card-text">
        <%= render 'form' %>
    </p>
    <%= link_to 'Ir a Atras', articles_path , :class => 'btn btn-success'%>
  </div>
</div>
</center>
</div>

app/views/articles/show.html.erb
<div class="container">
<div class="card">
  <div class="card-body">
        
        <p>
            <strong>Title:</strong>
            <%= @article.title %>
        </p>
        
        <p>
            <strong>Text:</strong>
            <%= @article.text %>
        </p>


        <div class="row">
            <div class="col">

                <div class="list-group">
                    <a href="#" class="list-group-item list-group-item-action active">
                        Files DownLoad
                    </a>
                    <% if @article.attachments? %>
                      <% @article.attachments.each do |attachment| %>
                        <a class="list-group-item list-group-item-action">
                            <%=  link_to(image_tag('file_2.png', width: '30', height: '25', alt: 'File DownLoad'),
                                attachment.url, target: '_blank',
                                class: 'list-group-item list-group-item-action')%>
                        </a>
                      <% end %>
                    <% end %>
                </div>
            </div>
            <div class="col"></div>
        </div>

        <br><br>

        <%= render partial: 'comments/comments', locals: {commentable: @article} %>
        <%= render partial: 'comments/form', locals: {commentable: @article}%>


        <br><br>

        <%= link_to 'Edit', edit_article_path(@article), :class => 'btn btn-outline-primary btn-sm' %> |
        <%= link_to 'Back', articles_path, :class => 'btn btn-outline-success btn-sm' %>         
    </div>
</div>
</div>