config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  get 'home/index'

  get 'welcome/index'

  # get 'categories/:category_id', to: 'articles#index', as: :category

  resources :articles do
    resources :comments, module: :articles
  end

  resources :publications do
    resources :comments, module: :publications
  end

  resources :users do
    resources :emergencies, controller: :contacts, type: 'Emergency'
    resources :friends, controller: :contacts, type: 'Friend'
  end

  # resources :categories do
  #  resources :articles
  # end

  resources :verifieds do
    resources :users
    resources :articles
  end


  resources :surveys do

    resources :questions do
      resources :answer_options
    end

  end


  resources :messages

  root to: 'home#index'

end

app/models/answer_option.rb
class AnswerOption < ApplicationRecord
  belongs_to :question, dependent: :destroy
  has_many :answer_users
end

app/models/answer_user.rb
class AnswerUser < ApplicationRecord
  belongs_to :survey
  belongs_to :user
  belongs_to :answer_option
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord # rubocop:todo Style/Documentation
  # dependent: :destroy, actual como una eliminacion en cascada,,
  # en donde a  eliminar el padre (Article) se elimina de igual forma el hijo (Comment)

  has_many :comments, as: :commentable

  # has_and_belongs_to_many :categories #Relacion Many-to-Many a categorias

  has_many :verifieds
  has_many :users, through: :verifieds

  # Upload Attachements
  mount_uploaders :attachments, ImageUploader

  mount_uploaders :attachments, PdfUploader

  # rubocop:todo Style/AsciiComments
  # estamos validando un campo, para el title que sea de 5 caracteres (Tamaño)
  # rubocop:enable Style/AsciiComments
  validates :title, presence: true, length: { minimum: 5 }

  validates :text, presence: true, length: { minimum: 10 }

  def self.category_with(name)
    Category.find_by!(name: name).articles
  end

  def self.category_counts
    Category.select('categories.*, count(categories.Category_id) as count').joins(:categories).group('categories.Category_id')
  end

  def category_list
    categories.map(&:name).join(', ')
  end

  def category_list=(names)
    self.categories = names.split(',').map do |c|
      Category.where(name: c.strip).first_or_create!
    end
  end

  def self.search(search, page)
    where(['upper(title) like ?',
           "%#{search}%".upcase]).paginate(page: page, per_page: 5).order('title')
  end
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  # has_and_belongs_to_many :articles

  # validates :name, presence: true, length: { minimum: 15 }
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :commentable, polymorphic: true

  belongs_to :article

  validates :commenter, presence: true

  validates :body, presence: true

end

app/models/contact.rb
class Contact < ApplicationRecord

  # Scopes
  scope :friends, -> { where(type: 'Friend') }
  scope :emergencies, -> { where(type: 'Emergency') }
end

app/models/emergency.rb
class Emergency < Contact < ApplicationRecord
  #Relaschip
  belongs_to :user

  #Validatios
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone_number, presence: true

end

app/models/friend.rb
class Friend < Contact < ApplicationRecord
  #Relaschip
  belongs_to :user

  #Validatios
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone_number, presence: true
end

app/models/message.rb
class Message < ApplicationRecord

  validates :text, presence: true, length: {minimum: 5}

  def message(msg1, ms2)

    [msg1, ms2].join(", ")

  end

end

app/models/note.rb
class Note < ApplicationRecord
end

app/models/publication.rb
class Publication < ApplicationRecord

  # relationships
  has_many :comments, as: :commentable

  #Scopes
  default_scope {order(created_at: :desc)} # Scope Default
  scope :with_long_name, -> (max, min){where('LENGTH(name) >= ? && LENGTH(name) < ?', min, max)} # With two parameters
  scope :with_long_name2, -> (length){where('LENGTH(name) >= ?', length)} # Scopes with arguments
  scope :date_today, -> {where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)} #Scopes with Range to the Dates
  scope :found_publications, ->  {where(status: 0)}
  scope :publication_wanted, -> {where(statuses.first(2).to_h)}
  scope :publication_return, -> {where(statuses.to_a.first(2).to_h)}

  #Scope as Class Method
  def self.with_name (name=20)
    where('name > ?', name)
  end


end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :survey, dependent: :destroy# Indicate that question have to survey
  has_many :answer_options
end

app/models/survey.rb
class Survey < ApplicationRecord

  has_many :questions, dependent: :destroy # Indicate that the survey have many to questions

  #Mapping to the answer_users (Many-to-Many)
  has_many :answer_users
  has_many :users, through: :answer_users

  #Validates Associations
  validates_associated :questions

  accepts_nested_attributes_for :questions, reject_if: :all_blank, allow_destroy: true





end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord # rubocop:todo Style/Documentation

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Relaschip
  has_many :verifieds
  has_many :articles, through: :verifieds
  has_many :questions
  has_many :emergencies, class_name: 'Emergency'
  has_many :friends, class_name: 'Friend'
  has_many :answer_users, dependent: :destroy
  has_many :surveys, through: :answer_users


  #Validations
  validates :email, presence: true
  validates :password, presence: true
end

app/models/verified.rb
# frozen_string_literal: true

class Verified < ApplicationRecord # rubocop:todo Style/Documentation
  belongs_to :article
  belongs_to :user
end

app/models/welcome.rb
class Welcome < ApplicationRecord
end

app/controllers/verifieds_controller.rb
# frozen_string_literal: true

# rubocop:todo Style/Documentation
class VerifiedsController < ApplicationController
  # Add Filters with Before_action
  before_action :set_verified, only: %i[show edit update]

  before_action :set_all_verified, only: [:index] # For Example

  def index; end

  def show; end

  def edit; end

  def new
    @verified = Verified.new
  end

  def create
    @verified = Verified.new(verified_params)

    if @verified.save
      flash[:msg] = 'It saved successfully'
      redirect_to @verified
    else
      flash[:msg] = "It dont't saved successfully"
      redirect_to :new
    end
  end

  def update
    if @verified.update(verified_params)
      redirect_to @verified
    else
      redirect_to :edit
    end
  end

  def destroy
    @verified = Verified.find(params[:id])
    @verified.destroy

    redirect_to verified_path
  end

  private

  def verified_params
    params.require(:verified).permit(:article_id, :user_id, :date, :comment)
  end

  def set_verified
    @verified = Verified.find(params[:id])
  end

  def set_all_verified
    @verifieds = Verified.all

    respond_to do |format|
      format.html # index.html-erb
      format.xml { render xml: @verifieds }
      format.json { render json: @verifieds }
    end
  end
end
# rubocop:enable Style/Documentation

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper # rubocop:todo Style/Documentation
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper # rubocop:todo Style/Documentation
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/verifieds_helper.rb
# frozen_string_literal: true

module VerifiedsHelper # rubocop:todo Style/Documentation
  def getDateTime # rubocop:todo Naming/MethodName
    Time.now.strftime('%d-%m-%Y %H:%M')
  end
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper # rubocop:todo Style/Documentation
end

app/views/verifieds/_form.html.erb
<%= form_with  model: @verified, local: true do |form| %>
  
  <% if @verified.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@verified.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @verified.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <p>
      <%= form.label :article_id %><br>
      <%= 
            form.collection_select :article_id, Article.order(:title).all, :id, :title, 
            class: "form-control", 
            prompt: "Seleccione Articulo" 
      %>
    </p>

    <p>
        <%= form.label :user_id %><br>
        <%= 
              form.collection_select :user_id, User.order(:email).all, :id, :email, 
              class: "form-control", 
              prompt: "Seleccione Usuario" 
        %>
    </p>

    <div>
      <%= form.label :date %>
      <%= form.datetime_select :date %>
    </div>
   
    <p>
      <%= form.label :comment %><br>
      <%= form.text_area :comment, :class => "form-control" %>
    </p>
     
    <p>
      <%= form.submit 'Guardar', :class => 'btn btn-outline-primary btn-sm' %>
    </p>

    
   
  <% end %>
  

app/views/verifieds/edit.html.erb
<h1>Edit Verified</h1>
 

<%= render 'form' %>

 
<%= link_to 'Back', surveys_path %>

app/views/verifieds/index.html.erb
<div class="container">
<br><br>
<table class="table table-bordered">
    <thead>
        <tr>
        <th>Article</th>
        <th>User</th>
        <th>Date</th>
        <th>Comment</th>
        <th colspan="3"></th>
        </tr>
    </thead>
        <tbody>
            <% @verifieds.each do |verified| %>
            <tr>
                <td><%= verified.article.title %></td>
                <td><%= verified.user.email %></td>
                <td><%= verified.date %></td>
                <td><%= verified.comment %></td>
                <td>
                    <%= link_to 'Show', verified_path(verified), class: 'btn btn-outline-primary btn-sm' %>
                </td>
                
                <td>
                    <%= link_to 'Edit', edit_verified_path(verified), class: 'btn btn-outline-warning btn-sm' %>
                </td>
                
                <td>
                    <%= link_to 'Destroy', verified_path(verified), 
                            method: :delete,
                            data: { confirm: 'Are you Sure?' }, 
                            class: 'btn btn-outline-danger btn-sm'
                    %>
                </td>
            </tr>
        <% end %>
        </tbody>
</table>
<br>

<%= link_to 'New Verified', new_verified_path, :class => 'btn btn-outline-primary btn-sm' %>

</div>

app/views/verifieds/new.html.erb
<div class="container" style="margin-top: 30px;">
<div class="card">
  <h5 class="card-header">New Verified</h5>
  <div class="card-body">
    <p class="card-text">
        <%= render 'form' %>
    </p>
    <%= link_to 'Back', verifieds_path, :class => 'btn btn-success'%>
  </div>
</div>
</div>

app/views/verifieds/show.html.erb
<p>
<strong>Article:</strong>
<%= @verified.article.title %>
</p>

<p>
<strong>User:</strong>
<%= @verified.user.email %>
</p>

<p>
<strong>Date:</strong>
<%= @verified.date %>
</p>

<p>
<strong>Comment:</strong>
<%= @verified.comment %>
</p>

<%= link_to 'Edit', edit_verified_path(@verified) %> |
<%= link_to 'Back', verifieds_path %>