config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  get 'home/index'

  get 'welcome/index'

  # get 'categories/:category_id', to: 'articles#index', as: :category

  resources :articles do
    resources :comments, module: :articles
  end

  resources :publications do
    resources :comments, module: :publications
  end

  resources :users do
    resources :emergencies, controller: :contacts, type: 'Emergency'
    resources :friends, controller: :contacts, type: 'Friend'
  end

  # resources :categories do
  #  resources :articles
  # end

  resources :verifieds do
    resources :users
    resources :articles
  end


  resources :surveys do

    resources :questions do
      resources :answer_options
    end

  end


  resources :messages

  root to: 'home#index'

end

app/models/answer_option.rb
class AnswerOption < ApplicationRecord
  belongs_to :question, dependent: :destroy
  has_many :answer_users
end

app/models/answer_user.rb
class AnswerUser < ApplicationRecord
  belongs_to :survey
  belongs_to :user
  belongs_to :answer_option
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord # rubocop:todo Style/Documentation
  # dependent: :destroy, actual como una eliminacion en cascada,,
  # en donde a  eliminar el padre (Article) se elimina de igual forma el hijo (Comment)

  has_many :comments, as: :commentable

  # has_and_belongs_to_many :categories #Relacion Many-to-Many a categorias

  has_many :verifieds
  has_many :users, through: :verifieds

  # Upload Attachements
  mount_uploaders :attachments, ImageUploader

  mount_uploaders :attachments, PdfUploader

  # rubocop:todo Style/AsciiComments
  # estamos validando un campo, para el title que sea de 5 caracteres (Tamaño)
  # rubocop:enable Style/AsciiComments
  validates :title, presence: true, length: { minimum: 5 }

  validates :text, presence: true, length: { minimum: 10 }

  def self.category_with(name)
    Category.find_by!(name: name).articles
  end

  def self.category_counts
    Category.select('categories.*, count(categories.Category_id) as count').joins(:categories).group('categories.Category_id')
  end

  def category_list
    categories.map(&:name).join(', ')
  end

  def category_list=(names)
    self.categories = names.split(',').map do |c|
      Category.where(name: c.strip).first_or_create!
    end
  end

  def self.search(search, page)
    where(['upper(title) like ?',
           "%#{search}%".upcase]).paginate(page: page, per_page: 5).order('title')
  end
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  # has_and_belongs_to_many :articles

  # validates :name, presence: true, length: { minimum: 15 }
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :commentable, polymorphic: true

  belongs_to :article

  validates :commenter, presence: true

  validates :body, presence: true

end

app/models/contact.rb
class Contact < ApplicationRecord

  # Scopes
  scope :friends, -> { where(type: 'Friend') }
  scope :emergencies, -> { where(type: 'Emergency') }
end

app/models/emergency.rb
class Emergency < Contact < ApplicationRecord
  #Relaschip
  belongs_to :user

  #Validatios
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone_number, presence: true

end

app/models/friend.rb
class Friend < Contact < ApplicationRecord
  #Relaschip
  belongs_to :user

  #Validatios
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone_number, presence: true
end

app/models/message.rb
class Message < ApplicationRecord

  validates :text, presence: true, length: {minimum: 5}

  def message(msg1, ms2)

    [msg1, ms2].join(", ")

  end

end

app/models/note.rb
class Note < ApplicationRecord
end

app/models/publication.rb
class Publication < ApplicationRecord

  # relationships
  has_many :comments, as: :commentable

  #Scopes
  default_scope {order(created_at: :desc)} # Scope Default
  scope :with_long_name, -> (max, min){where('LENGTH(name) >= ? && LENGTH(name) < ?', min, max)} # With two parameters
  scope :with_long_name2, -> (length){where('LENGTH(name) >= ?', length)} # Scopes with arguments
  scope :date_today, -> {where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)} #Scopes with Range to the Dates
  scope :found_publications, ->  {where(status: 0)}
  scope :publication_wanted, -> {where(statuses.first(2).to_h)}
  scope :publication_return, -> {where(statuses.to_a.first(2).to_h)}

  #Scope as Class Method
  def self.with_name (name=20)
    where('name > ?', name)
  end


end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :survey, dependent: :destroy# Indicate that question have to survey
  has_many :answer_options
end

app/models/survey.rb
class Survey < ApplicationRecord

  has_many :questions, dependent: :destroy # Indicate that the survey have many to questions

  #Mapping to the answer_users (Many-to-Many)
  has_many :answer_users
  has_many :users, through: :answer_users

  #Validates Associations
  validates_associated :questions

  accepts_nested_attributes_for :questions, reject_if: :all_blank, allow_destroy: true





end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord # rubocop:todo Style/Documentation

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Relaschip
  has_many :verifieds
  has_many :articles, through: :verifieds
  has_many :questions
  has_many :emergencies, class_name: 'Emergency'
  has_many :friends, class_name: 'Friend'
  has_many :answer_users, dependent: :destroy
  has_many :surveys, through: :answer_users


  #Validations
  validates :email, presence: true
  validates :password, presence: true
end

app/models/verified.rb
# frozen_string_literal: true

class Verified < ApplicationRecord # rubocop:todo Style/Documentation
  belongs_to :article
  belongs_to :user
end

app/models/welcome.rb
class Welcome < ApplicationRecord
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

  #before_action :set_survey, only: %i[show ]

  before_action :authenticate_user!

  before_action :set_all_surveys, only:  :index

  before_action :set_survey, only: %i[ show edit update destroy]

  def index; end

  def new
    @survey = Survey.new
    @survey.questions.build
  end

  # surveys#edit
  # edit_surveys GET /surveys/edit
  def edit
  end

  def show
  end

  def create
    @survey = Survey.new(survey_params)
    @survey.questions.first
    respond_to do |format|
      if @survey.save
        flash[:msg] = 'It saved successfully'
        format.html { redirect_to @survey }
        format.xml {render xml: @survey }
        format.json {render json: @survey }
      else
        flash[:msg] = "It dont't saved successfully"
        render :new
      end
    end
  end

  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html{redirect_to survey_path(@survey), notice: 'Update was survey Successfully'}
        format.json{render json: @survey}
      else
        format.html{render :edit}
      end
    end
  end

  def destroy
    @survey.destroy
    respond_to do |format|
      format.html{redirect_to survey_url, notice: 'Destroy was survey successfully'}
      format.json{render json: @survey}
    end
  end

  private

      def set_all_surveys
        @surveys = Survey.order('created_at ASC').all
      end

      def set_survey
        @survey = Survey.find(params[:id])
      end

      def survey_params
        params.require(:survey).permit(:survey_name, :survey_desc,
                                       questions_attributes:[:id, :question, :_destroy])
      end
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper # rubocop:todo Style/Documentation
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper # rubocop:todo Style/Documentation
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper # rubocop:todo Style/Documentation
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper # rubocop:todo Style/Documentation
end

app/views/surveys/_form.html.erb
<%= form_for  @survey, local: true do |form| %>

  <div>
    <%= form.label :survey_name %>
    <%= form.text_field :survey_name, class: "form-control" %>
  </div>

  <p>
    <%= form.label :survey_desc %><br>
    <%= form.text_area :survey_desc, class: "form-control" %>
  </p>

  <div class="form-group">
    <h4>Add Questions: </h4>
    <%= form.fields_for :questions do |question| %>
      <%= render 'questions', form: question %>
    <% end %>
  </div>

  <%= link_to_add_association 'Add Question', form, :questions %>

  <p>
    <%= form.submit 'Save', class: 'btn btn-outline-primary btn-sm' %>
  </p>

<% end %>

app/views/surveys/_question_fields.html.erb
<div class="row">
  <div class="col">
    <b><%= f.label :question, 'Add Question: '%></b>
  </div>
    <div class="col">
        <%= f.text_field :question, class: 'form-control', placeholder: 'Add the Question?' %>
    </div>
    <div class="col">
      <%= link_to_remove_association 'Remove Question', f, class: 'btn btn-danger btn-sm' %>
    </div>
    <br><br><br>
</div>

app/views/surveys/_questions.html.erb
<div class="form-group">
  <%= form.label :question %>
  <%= form.text_field :question %>
  <%= link_to_remove_association 'Remove Question', form %>
</div>

app/views/surveys/edit.html.erb
<h1>Edit Survey</h1>


<%= render 'form' %>


<%= link_to 'Back', survey_path, class: 'btn btn-success btn-sm' %>

app/views/surveys/index.html.erb
<div class="container">
  <br><br>
  <table class="table table-bordered">
    <thead>
    <tr>
      <th></th>
      <th>ID</th>
      <th>Survey Name</th>
      <th>Survey Description</th>
      <th colspan="3"></th>
    </tr>
    </thead>
    <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td>
          <center>
            <%= link_to 'Question(' +survey.questions.count.to_s+')', survey_questions_path(survey), class: 'btn btn-info btn-sm' %>
          </center>
        </td>
        <td><%= link_to survey.id, survey_path(survey) %></td>
        <td><%= survey.survey_name %></td>
        <td><%= survey.survey_desc %></td>

        <td>
          <center>
          <div class="btn-group">
            <button type="button" class="btn btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Admin
            </button>
            <div class="dropdown-menu">
              <a><%= link_to 'Show', survey_path(survey), class: 'dropdown-item' %></a>
              <a><%= link_to 'Edit', edit_survey_path(survey), class: 'dropdown-item' %></a>
              <a>
                <%= link_to 'Destroy', survey_path(survey),
                            method: :delete,
                            data: { confirm: 'Are you Sure?' },
                            class: 'dropdown-item'
                %>
              </a>
            </div>
          </div>
          </center>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <br>

  <%= link_to 'New Survey', new_survey_path, class: "btn btn-primary"%>

  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <%= render 'show' %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>


</div>

app/views/surveys/new.html.erb
<div class="container" style="margin-top: 30px;">
  <div class="card">
    <h5 class="card-header">New Verified</h5>
    <div class="card-body">
      <p class="card-text">
        <%= render 'form' %>
      </p>
      <%= link_to 'Back', surveys_path, class: 'btn btn-success'%>
    </div>
  </div>
</div>

app/views/surveys/show.html.erb
<div class="container">
  <center>
    <div class="card border-info mb-3" style="max-width: 30rem; margin-top: 100px;">
      <div class="card-header">Header</div>
      <div class="card-body">
        <h5 class="card-title"></h5>
        <p class="card-text">
              <p>
                <strong>Survey Name: </strong>
                <%= @survey.survey_name %>
              </p>

              <p>
                <strong>Survey Description:</strong>
                <%= @survey.survey_desc %>
              </p>

              <p>
                  <div class="list-group">
                    <button type="button" class="list-group-item list-group-item-action active">
                      <h5><b>Questions</b></h5>
                    </button>
                    <% for @question in @survey.questions %>
                      <button type="button" class="list-group-item list-group-item-action">
                        <%= @question.question %>
                      </button>
                    <% end %>
                  </div>
              </p>
        </p>
      </div>
      <div class="card-footer bg-transparent border-info">
        <%= link_to 'Edit', edit_survey_path(@survey), class: 'btn btn-outline-warning btn-sm' %> |
        <%= link_to 'Back', surveys_path, class: 'btn btn-outline-success btn-sm'  %>
      </div>
    </div>
  </center>
</div>