config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  get 'home/index'

  get 'welcome/index'

  # get 'categories/:category_id', to: 'articles#index', as: :category

  resources :articles do
    resources :comments, module: :articles
  end

  resources :publications do
    resources :comments, module: :publications
  end

  resources :users do
    resources :emergencies, controller: :contacts, type: 'Emergency'
    resources :friends, controller: :contacts, type: 'Friend'
  end

  # resources :categories do
  #  resources :articles
  # end

  resources :verifieds do
    resources :users
    resources :articles
  end


  resources :surveys do

    resources :questions do
      resources :answer_options
    end

  end


  resources :messages

  root to: 'home#index'

end

app/models/answer_option.rb
class AnswerOption < ApplicationRecord
  belongs_to :question, dependent: :destroy
  has_many :answer_users
end

app/controllers/answer_options_controller.rb
class AnswerOptionsController < ApplicationController

  before_action  :set_answer_option, only: %i[show index new update destroy create]

  def index
    @answer_options = @question.answer_options.all
  end

  def new
    @answer_option = AnswerOption.new
  end

  def show
  end

  # GET    /surveys/:survey_id/questions/:question_id/answer_options/:id/edit(.:format)
  def edit
    @question = Question.find(params[:id])
    @answer_option = @question.questions.find(params[:id])
  end

  def create
    @answer_option = AnswerOption.new(answer_option_params)
    @answer_option.question_id = @question.id
    respond_to do |format|
      if @answer_option.save
        format.html {redirect_to survey_question_answer_options_path(@question), notice: 'Answer Option was successfully created'}
        format.json {render :show, status: :created}
      else
        format.html{render :new}
        format.json{render json: @answer_option, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @answer_option.destroy
    respond_to do |format|
      format.html{redirect_to survey_question_answer_options_url(@question), notice: 'Question was Success'}
      format.json {head :no_content }
    end
  end

  def update
    respond_to do |format|
      if @answer_option.update(answer_option_params)
        format.html{redirect_to survey_question_answer_options_path(@question), notice: 'Engineer was successfully'}
        format.json{render json: @answer_option}
      else
        format.html{redirect_to :edit}
      end
    end
  end

  private

  def set_answer_option
    #/surveys/:survey_id/questions/:question_id/answer_options/:id/edit(.:format)
    @survey = Survey.find(params[:id]) #recupere the survey
    @question = Question.find(params[:question_id]) # Recuperate  the question
    @answer_option = AnswerOption.find(params[:id]) if params[:id]#Recuperate the question, only if send's
  end

  def answer_option_params
    params.require(:answer_option).permit(:text, :question_id)
  end

end

app/helpers/answer_options_helper.rb
module AnswerOptionsHelper
end

app/views/answer_options/_form.html.erb
<%= form_with(model: [@survey, @question, @answer_option], local: true) do |form| %>

  <div>
    <%= form.label :text %>
    <%= form.text_field :text, class: "form-control" %>
  </div>

  <p>
    <%= form.label :question_id %><br>
    <%=
      form.collection_select :question_id, Question.all, :id, :question,
                             prompt: "Select Question", class: "forml-control"
    %>
  </p>
  <p>
    <%= form.submit 'Save', class: 'btn btn-outline-primary btn-sm'  %> |
    <%= link_to 'Cancel', survey_question_answer_options_path(@question), class: 'btn btn-outline-secondary btn-sm' %>
  </p>



<% end %>

app/views/answer_options/edit.html.erb
<h1>Edit Question</h1>


<%= render 'form' %>


<%= link_to 'Back', answer_options_path %>

app/views/answer_options/index.html.erb
<div class="container">
  <br><br>
  <table class="table table-bordered">
    <thead>
    <tr>
      <th>ID</th>
      <th>Text</th>
      <th>Question</th>
      <th colspan="3"></th>
    </tr>
    </thead>
    <tbody>
    <% @answer_options.each do |answer_option| %>
      <tr>

        <td><%= answer_option.id %></td>
        <td><%= answer_option.text %></td>
        <td><%= answer_option.question.question %></td>

        <td>
          <%= link_to 'Edit', class: 'btn btn-outline-warning btn-sm' %>
        </td>

        <td>
          <%= link_to 'Destroy',
                      method: :delete,
                      data: { confirm: 'Are you Sure?' },
                      class:  'btn btn-outline-danger btn-sm'
          %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <br>

  <%= link_to 'New Answer Options', new_survey_question_answer_option_path(@question), :class => 'btn btn-outline-primary btn-sm' %>

</div>

app/views/answer_options/new.html.erb
<div class="container" style="margin-top: 30px;">
  <div class="card">
    <h5 class="card-header">New Verified</h5>
    <div class="card-body">
      <p class="card-text">
        <%= render 'form' %>
      </p>
      <%= link_to 'Back', survey_question_answer_options_path, :class => 'btn btn-outline-success btn-sm'%>
    </div>
  </div>
</div>

app/views/answer_options/show.html.erb
<div class="container">
  <center>
    <div class="card border-info mb-3" style="max-width: 30rem; margin-top: 100px;">
      <div class="card-header">Header</div>
      <div class="card-body">
        <h5 class="card-title"></h5>
        <p class="card-text">
        <p>
          <strong>Text: </strong>
          <%= @question.question%>
        </p>

        <p>
          <strong>Question:</strong>
          <%= @question.question.question %>
        </p>
        </p>
      </div>
      <div class="card-footer bg-transparent border-info">
        <%= link_to 'Edit', edit_survey_question_answer_option_path, class: 'btn btn-outline-warning btn-sm' %> |
        <%= link_to 'Back', survey_question_answer_option_path, class: 'btn btn-outline-success btn-sm'  %>
      </div>
    </div>
  </center>
</div>